import java.util.HashMap;
import java.util.Map;

/*
* Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class FindTheDifference389 {

public static void main(String args[]){
    String s= "abcd";
    String t = "abcde";

    Map<Character,Integer> map = new HashMap<>();

    for(char c : s.toCharArray()){
        map.put(c,map.getOrDefault(c,0)+1);
    }

    for(char c : t.toCharArray()){
        map.put(c,map.getOrDefault(c,0)-1);
    }

    for (char c: map.keySet()) {
        if(map.get(c)!=0){
            return;
        }
    }


}

}
